# If relative path given, it should relative to working directory (instead of project root, etc).
# Those directories should be manually created before executing programs.
path:
  # Data root directory, should include "train" and "test" sub-directory.
  # It should also includes "train_splitted" and "val_splitted" after running split_train_val.py.
  DATA_DIR: "../data"

  # Model checkpoint and category-id mapping file directory.
  MODEL_DIR: "../model"

  # Inference file (both .npz and .zip) output directory.
  OUTPUT_DIR: "../output"

data:
  N_VAL_DATA: 400

train: 
  BATCH_SIZE: 2
  LEARNING_RATE: 0.0001
  MAX_EPOCHES: 30

  # If enabled, training will stop if the validation loss increases in the last two epochs.
  EARLY_STOP: true